### ISSUE TITLE
[RFC] Drop support for unmaintained PHP and Symfony versions

### ISSUE THREAD

**Issue by PabloKowalczyk** [thephpleague/tactician-bundle#110]
As discussion started in https://github.com/thephpleague/tactician-bundle/pull/109, IMO there is no need to support PHP 7.0 (already EOL) and Symfony 3.3 (also EOL), mentioned versions are not supported by their creators so why we should support them?

@rosstuck also mention to drop support for Symfony 2.8 LTS, this version is still supported, but only with security fixes, until November 2019, almost whole year from now. IMO drop is possible but only with new major version to avoid confusion about not supporting supported LTS version.

Maybe a next major with PHP7.1+ and Syfmony 3.4+/4.1+ support is a good idea? But this means that `v1` should be supported until Nov 2019 - end of support for 2.8 LTS.

WDYT?

**EDIT:**
PHP roadmap: http://php.net/supported-versions.php
Symfony roadmap: https://symfony.com/roadmap

**Comment by rosstuck** [comment]
For the sake of clarity, I'm thinking about doing a Tactician2 that's 7.1+ only (for object typehints and a few other things), which will mean changing some of the core interfaces. If possible, I'd prefer to do the big wave of version deprecations all in one go so this goes into planning with a few other things.

As for Symfony 2.8, it's quite outdated and in support only mode. If folks are still using it, they can continue to use version 1.X of this bundle, the code won't stop working for them but I don't think there's many projects still using Tactician with 2.8 and still doing active development.

**Comment by PabloKowalczyk** [comment]
Overall, I agree with you. I could provide PR to drop old PHP/Symfony versions.

> As for Symfony 2.8, it's quite outdated and in support only mode. If folks are still using it, they can continue to use version 1.X of this bundle, the code won't stop working for them but I don't think there's many projects still using Tactician with 2.8 and still doing active development.

New major version of this bundle, without support for Symfony 2.8, sounds good. Probably will lead to some simplifications and some BC layers removed - less code means better maintainability :)

**Comment by acasademont** [comment]
I think this can be cloused now :)

**Comment by PabloKowalczyk** [comment]
Yep, fine for me :)
