### ISSUE TITLE
PHP 7.4 - reflectiontype::__toString deprecated

### ISSUE THREAD

**Issue by drekinov** [thephpleague/tactician-bundle#117]
https://github.com/thephpleague/tactician-bundle/blob/e1e8f9975cb689fbd978a72aa79b5d01e787fc63/src/DependencyInjection/HandlerMapping/TypeHintMapping.php#L65
In just released php 7.4.0 __toString is deprecated. 
https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.reflection

**Comment by rosstuck** [comment]
Should be resolved in e5ef06598723ae33adf906b223e9307ff3728166, I hope :)
