### ISSUE TITLE
Adding Command Events support

### ISSUE THREAD

**Issue by pawelbaranski** [thephpleague/tactician-bundle#12]
Hello,

I mean [this plugin](https://tactician.thephpleague.com/plugins/command-events), how about it ? I'd welcome it with open arms :) Is it planned or maybe under development ?

**Comment by rosstuck** [comment]
Hi @pawelbaranski, it's not planned to integrate into tactician-bundle at this time. A lot of what you'd normally use events for can be achieved with custom middleware instead. 

Just curious, what kind of integration would you like to see? Tags for listeners/subscribes? Thanks!

**Comment by pawelbaranski** [comment]
I personally prefer to keep such settings in bundle configuration, similar to how it is done in the tactician-bundle (commandbus/middleware setting). I think it is more readable than having tags spread all over different bundles, but I wouldn't mind if tags were used.

Out of curiosity, can you direct me to an example of such custom middleware you mentioned ?

**Comment by rosstuck** [comment]
Sure, there's a manual page for custom middleware here: http://tactician.thephpleague.com/middleware/ With an approach like this, you can perform actions before, after or on failure (try/catch) the next middleware in the chain and the order of operations is very explicit in the bundle configuration.

Let me know if that helps and then I can update this ticket accordingly. :smile:
