### ISSUE TITLE
Tag new release to support PHP 7.4

### ISSUE THREAD

**Issue by ruudk** [thephpleague/tactician-bundle#120]
Would be really great to have https://github.com/thephpleague/tactician-bundle/commit/e5ef06598723ae33adf906b223e9307ff3728166 tagged 🙏

**Comment by rosstuck** [comment]
PHP 7 doesn't have ReflectionType->getName()`so will need detect this as I don't want to drop version until the Symfony2.0 release :weary: 

Will push again in a bit.

**Comment by rosstuck** [comment]
Okay, tagged v1.1.17, hopefully that'll do the trick. If so, please close the ticket. :)

**Comment by ruudk** [comment]
Thanks!!
