### ISSUE TITLE
Make CompilerPass tests less brittle/dependent on internal implementation details of compiler pass

### ISSUE THREAD

**Issue by benglass** [thephpleague/tactician-bundle#22]
See discussion in PR #20 

Current use of mockery for testing compiler pass means test is heavily dependent on the specific implementation of the compiler pass. The tests verify that all of the methods on $container are called as a means of ensuring that certain services are created.

Instead it might be more robust to use something like:
https://github.com/matthiasnoback/SymfonyDependencyInjectionTest#testing-a-compiler-pass

This would allow testing that the desired side effects occur (services are created) instead of testing the implementation and interaction with the $container

**Comment by rosstuck** [comment]
While there's still room for improvement, we've come a LONG way since the early days of the Mockery based tests and I feel we can legitimately close this one now.

Thanks again @benglass :)
