### ISSUE TITLE
Add security support

### ISSUE THREAD

**Issue by RonRademaker** [thephpleague/tactician-bundle#23]
What do you think about adding symfony security middleware out of the box in the bundle. I'm thinking some kind of middleware that does an ```isGranted``` call before passing on the ```$command```.

**Comment by rosstuck** [comment]
Hi Ron, sorry for the late reply, vacation. :smile: This is definitely something I'm interested in adding, I've discussed it with folks a few times but I haven't quite decided if it's worth splitting out into a different package for interfaces and then put the adapter here or something similar. If you've got any thoughts, let me know. Alternately, if you have something working alreay, we can talk about it over a PR. Thanks! :)

**Comment by RonRademaker** [comment]
Hope you had fun and enjoyed the airplane food ;)

An interface for security checks sounds like something that could be a PSR recommendation. I think it could enhance interoperability between frameworks and libraries, so we shouldn't making one up just for tactician. I don't know if there is work done or in progress in that regard.

For this purpose, this is the symfony bundle so being symfony specific should be acceptable I think. I can create a PR.

**Comment by rosstuck** [comment]
Still on vacation but thanks :+1: 

I'm mainly interested in looking if a Tactician level interface makes sense but not really sure. That said, better to have something then nothing so if you'd like to issue a PR, I think it'd be a great starting point. :)
