### ISSUE TITLE
Validator Middleware is not compatible with Symfony 2.3

### ISSUE THREAD

**Issue by rdohms** [thephpleague/tactician-bundle#26]
Turns out our advertised compatibility with Symfony 2.3 is not correct.

`Symfony\Component\Validator\Validator\ValidatorInterface;` used in the `ValidatorMiddlware` is actually not available until 2.5, it is formerly known as `Symfony\Component\Validator\ValidatorInterface;`

Thinking what approach is best here.

**Comment by rosstuck** [comment]
I'd vote to just upgrade the requirements to 2.8.

**Comment by rdohms** [comment]
Given anything below 2.7 is now gone, and 2.8 is the new LTS, I agree.

**Comment by RonRademaker** [comment]
#24 drops support for any symfony version older than 2.8

**Comment by rosstuck** [comment]
Indeed resolved by #24
