### ISSUE TITLE
Multiple bus but one locator ?

### ISSUE THREAD

**Issue by tyx** [thephpleague/tactician-bundle#27]
Hi guys,

I wanted to keep using this great tactician to manage also my queries in addition to my commands.

So I decided to create a second bus as specified in the doc but I just realized that the locator still unique. So I cannot attach a handler to a specific bus ? All the buses could handle all commands ? I'm not fan.

Does it bothers someone that I make a PR to change this behavior ?
The tag would evolve in something like 
```            
<tag name="tactician.handler" bus="default" command="My\Command" />
```

We could also attach by default (no bus attribute specified) to all locators to keep BC if someone currently use same command through different buses.

Let me know if I miss something.

**Comment by rosstuck** [comment]
Sounds pretty reasonable to me. :)

**Comment by tyx** [comment]
Great. Currently on holidays I will have a try when I will be back.

**Comment by rosstuck** [comment]
On a related note, I got a request yesterday to be able to set an inflector per bus as well. Perhaps we should rejigger the build/config system a bit in general?

But for now, ignore that and enjoy a well deserved holiday! :smile:

**Comment by tyx** [comment]
I will start to work on it. 

> an inflector per bus as well

Same here, we need it !

**Comment by tyx** [comment]
Let's go on #29
