### ISSUE TITLE
[RFC] Add a method to base controller to handle commands

### ISSUE THREAD

**Issue by borNfreee** [thephpleague/tactician-bundle#28]
Hi,

### Problem

I don't like to write `$commandBus = $this->get('tactitian.commandbus');` for each action of my controller

### Proposed solution

Are you interested in a new method for base controller to handle commands (for those who are not using controller as a service)?

Something like this:

```php
$this->handleCommand($command);
```

or even this

```php
$this->handle($command);
```

It can be achieved for example by using a Trait.

It would be just a shortcut to save one line of code per action

**Comment by rosstuck** [comment]
Hi @borNfreee! Thanks for using Tactician and taking the time to write a super clear ticket, I really appreciate it. :)

After thinking about it last night, I feel this is a totally legit solution for individual projects to implement but I'm hesitant to put it in the core project. It typically leads to folks seeing it as "the blessed way". Most Symfony projects I've seen end up putting together their own base controllers with their own conventions and this is a really small thing to write, so I'd rather encourage folks to stitch it together in a way they're comfortable with. Also, I have to admit I'm a bit averse to using traits for anything related to DI (as a rule of thumb).

I totally get it as a quality of life improvement but I'd rather not add it at this time. I'll close the ticket for now but if you have any alternate ideas, feel free to comment and we can discuss further. :)

Finally, please don't let this put you off submitting more ideas. If you have any other Developer Experience ideas or improvements, please feel free to open tickets for them. A lot of good stuff comes out of feedback like this. Thanks again. :)

**Comment by borNfreee** [comment]
No problem, thank you for detailed answer 👍
