### ISSUE TITLE
Add support for bernard queue

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-bundle#30]
Would you accept a PR for that?

**Comment by rosstuck** [comment]
I'd be interested, especially once multi-bus support is finished soon and provided Bernard has reached a stable enough state that it can be relied on going forward everywhere (I know it was still in flux a lot last year but haven't looked much since :smile: )

**Comment by sagikazarmark** [comment]
I am trying to put effort in bernard as well. As far as I can see some generic project decisions need to be made (code organization, some changes in the abstraction, etc), but hopefully we will get there soon.

**Comment by rosstuck** [comment]
Sounds good to me. I'm swamped right now because DomCode is this Friday ( :sweat_smile: ) but having had a year more experience now with this now, maybe it would be good to sit down on Hangouts or something in November and plot a course together, including the plugin as well. :smile:

**Comment by rosstuck** [comment]
Closing this one due to inactivity and maybe something to think about on a more fundamental level with Tactician2. :)

**Comment by sagikazarmark** [comment]
Yeah, nothing really happened during this one year on this front.

Is Tactician 2 coming?

**Comment by rosstuck** [comment]
I have some ideas in my notebook for it but I'm not sure there's a lot of demand.

My current idea is to mainly drop some features (get_class everywhere, no more ClassNameExtractors) and add a Router object to core. Bring PSR-11 container support to core. Stuff like that.

After a couple years of maintaining the different packages, I feel like there's way too many moving parts in all the packages for something that should be so darn simple. I want to see how the changes in this bundle are received and then look at bringing Tactician back to something really really tight.
