### ISSUE TITLE
Regressions in Config

### ISSUE THREAD

**Issue by rosstuck** [thephpleague/tactician-bundle#31]
After merging several large changes, there's a number of issues popping up with bundle config.

For example, the config currently assumes `default_bus` is always set and errors out if it doesn't. There's no test checking this.

After resolving that, it fails out because the commandbus index isn't seen because it's one level lower in a repeating array now. I'm sure there's more issues that need to be resolved if I keep digging.

These appear in a fresh symfony project setup, not when working on the bundle in isolation. They all need to be fixed before tagging a release.

**Comment by tyx** [comment]
In fact, we misused the `getExtensionConfig` here https://github.com/thephpleague/tactician-bundle/blob/master/DependencyInjection/Compiler/CommandHandlerPass.php#L26

It seems it does not get mergedConfig but only original config set by user. (so without default configuration)

We should register `default_bus` and other stuff into parameter I guess, to be able to use them in the CompilerPass.

IMO The best way to test that part still behat. I will be available next week to have a look.

**Comment by tyx** [comment]
Done in https://github.com/thephpleague/tactician-bundle/pull/33

**Comment by rosstuck** [comment]
Merged.
