### ISSUE TITLE
Suggested namespace is too similar to one reserved for Symfony Console commands

### ISSUE THREAD

**Issue by teohhanhui** [thephpleague/tactician-bundle#38]
https://symfony.com/doc/current/console.html

AppBundle\Command vs AppBundle\Command**s**

It's best if we can find an alternative.

**Comment by rdohms** [comment]
I think this is a non-issue to be fair.

1. Symfony's choice of namespace is a very bad one, `Console` would have been better.
2. It is usually recommended to store commands outside of your framework structure

Plus we do not really recommend this, its only part of a simplified example if I'm not mistaken.
