### ISSUE TITLE
RFC: Autowiring commands to handlers in Symfony 3.3+

### ISSUE THREAD

**Issue by rosstuck** [thephpleague/tactician-bundle#44]
Based on the [new service discovery coming in Symfony 3.3](http://symfony.com/blog/new-in-symfony-3-3-psr-4-based-service-discovery), I'd like to add a naming convention based locator.

The idea is that we could use config like:

```
services:
    App\:
        resource: '../../src/{Handler}'
        tags: ['tactician.handler']
```

This would autowire all handlers into the DI container using their FQCN as service id (RegisterUserHandler).

The proposed new locator would automatically route a command with a FQCN like Foo\RegisterUser or Foo\RegisterUserCommand to Foo\RegisterUserHandler. We could pull that directly from the container/[service locator](https://github.com/thephpleague/tactician-bundle/pull/43) and presto, it works.

Pros:
- The user has all of their correct mappings in 3 lines of config, much less config typing, especially since IDEs don't autocomplete the command class name in services.yml
- No more worrying about updating the command names in the services.yml after doing a rename on a command.
- Much simpler onboarding for those using autowiring.

Cons:
- Much magic, such auto, very wow.
- We definitely need to add a switch to make this optional.
- Mainly works in Symfony 3.3 and up.

Thoughts:
- We could add a naming inflector interface for this autowiring so folks can add in their own class name conventions.

While I'm only so-so on autowiring containers and generally avoid it, I think this is a feature that pro-autowiring folks would really enjoy.

Thoughts? Totally open to all config format/feature/implementation suggestions here. :)

**Comment by ogizanagi** [comment]
It'll be great if it's also flexible enough & configurable out of the box. 
In my own projects, I declare commands in a `Command` namespace and handlers in a `Handler` one (it might seem redundant, but it helps well to keep my Application layer structured and not overwhelming).

E.g: `Foo\Application\Command\RegisterUserCommand` should be handled by `Foo\Application\Handler\RegisterUserHandler`

**Comment by tyx** [comment]
IMO everyone have its own habits regarding stuff naming. As @ogizanagi said we need this very flexible to be used.

In our apps, we have not dedicated handlers for example, so it becomes difficult to make magic I guess ;)

**Comment by ogizanagi** [comment]
Note that in the yaml configuration shown in the description:

```yml
services:
    App\:
        resource: '../../src/{Handler}'
        tags: ['tactician.handler']
```

the tag could also be completely removed if we introduce a marker interface, thanks to the autoconfigure capabilities of sf 3.3.
Above all, it also means you don't to write anything specific to handlers in the DI configuration, but simply keep the defaults proposed by the [framework recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/etc/packages/app.yaml#L14-L18) using flex to PSR-4 load the whole `src/` directory, and have everything configured & autowired automatically.

A similar marker is under discussion for [Twig runtimes](https://github.com/symfony/symfony/pull/23037), which currently don't have any interface either.

**Comment by kejwmen** [comment]
This is the tough one.

In my project we use notation like this:
`Foo\Application\User\RegisterUser\RegisterUser` for command and:
`Foo\Application\User\RegisterUser\RegisterUserHandler` for command handler.
Plus marker interfaces.

> We could add a naming inflector interface for this autowiring so folks can add in their own class name conventions.

Sounds great, with a few most popular implementations it can work really well.

If you need any help, I would be glad to.

**Comment by jvasseur** [comment]
If me add an handler interface maybe we could add a static method to it that gives the corresponding command to remove the need for an inflector.

**Comment by rosstuck** [comment]
We've experimented with marker interfaces in the early days of Tactician
and it never really worked out, so they were removed and won't return in
core, especially since a large number of folks will probably never use
autowiring.

That said, if folks want to build it themselves, I think we should make it
possible for them. (it's already possible today by writing a custom
HandlerLocator which isn't super hard)

**Comment by ogizanagi** [comment]
I think it's slightly different here. No need to be in the core. It'll only deserve autoconfiguring purpose, which is a symfony thing, thus should only be in the bundle. This marker interface should not deserve any other means.

**Comment by sgomez** [comment]
Besides, using a marker interface could be the best way to differentiate who wants to use autowiring or not.

**Comment by sgomez** [comment]
I was thinking that the Command can be guessed by reflection. So If we have:

```php
class MyCommandHandler {
    public function handler(MyCommandOrQuery $command) {}
}
```

We can guess the command class with:

```
$reflectionExtractor = new ReflectionExtractor();
$command = $reflectionExtractor
     ->getTypes($handlerClassName, $methodInflectorName)
     ->getClass()
     ->getName();
```

**Comment by marvinrabe** [comment]
Is it possible to read the Command from:

**Comment by rosstuck** [comment]
Closing in favor of #60 and the PR #67.
