### ISSUE TITLE
Tests no longer executed on travis

### ISSUE THREAD

**Issue by tyx** [thephpleague/tactician-bundle#45]
Just to let you know I just noticed that the tests are no longer ran on travis because of https://github.com/thephpleague/tactician-bundle/blob/master/phpunit.xml.dist#L14 (`Tests` folder was renamed to `tests`). 

I guess every people on mac just did not notice ;) and travis says it's not a big deal to have 0 test :D

I'm currently working on the PR to fix that

**Comment by rosstuck** [comment]
Heh, I'm on Linux but always type the full command so didn't see it.

Merged fix PR, thanks!
