### ISSUE TITLE
Adding Doctrine support

### ISSUE THREAD

**Issue by rosstuck** [thephpleague/tactician-bundle#6]
What would you all think about adding https://github.com/thephpleague/tactician-doctrine as a dependency for the bundle? That would let us ship with a default transaction middleware as all, which is a really useful thing to have out of the box.

**Comment by rdohms** [comment]
:+1:

**Comment by rosstuck** [comment]
Resolved in https://github.com/thephpleague/tactician-bundle/pull/7
