### ISSUE TITLE
Security middleware - command inheritance

### ISSUE THREAD

**Issue by mastercoding** [thephpleague/tactician-bundle#65]
Hi,

Would you be open to accept a PR that changed the behaviour of the security component, to check if the command is an instanceof any of the defined security commands, like this:

https://github.com/randock/tactician-bundle/commit/a9e07b08708a0e8f47cdcb9d95f45f77440cab6d

We made this change to allow for easier security config. With an AbstractAdminCommand, or AbstractUserCommand, you can then just configure two security roles instead of having to specify all the commands manually.

We use this currently to apply the lowest role to our abstract command. If you would consider a PR, i'll create a proper one with improved checking (so that it not takes the first one it encounters).

**Comment by rosstuck** [comment]
Hi @mastercoding, thanks for opening this issue!

What you've described makes sense in your app but, I have to admit, I'm a bit wary of doing this in the root library. If we apply an instanceof check here, we make it a bit too easy to have permissions that are looser than intended or even misleading. With the patch as given, you could have the command you want in the list but if the base class is further up the list, that mapping will be taken instead. Even if that's corrected AND changed to account for multiple levels of hierarchy, I'm not sure if it's easy/intuitive to read (which is something I really want in this type of security). 

So, I think this is probably best living in a custom voter for your application specifically. I'd definitely be open to us making this easier for you to implement though, without overriding/extending the entire bundle. If you have any thoughts on how we could do this (e.g. put the command mapping inside an object so you can get it from the container, change how we load the security middleware, etc), I'd be open to making changes for that. :)

**Comment by mastercoding** [comment]
Hi @rosstuck. Thanks for the reply. I will have a look this week at refactoring the code a bit so it can be easily configured and which allows us to remove our fork 👍

**Comment by rosstuck** [comment]
Hey @mastercoding, I'm guessing this turned out to be tougher than expected or life has caught up with you. :) I'm going to close this issue for now after 60 days or so but if anything else pops up or you'd like to discuss it more, feel free to reopen.

Thanks again for your time!
