### ISSUE TITLE
Multi bus mapping issue

### ISSUE THREAD

**Issue by jorge07** [thephpleague/tactician-bundle#94]
I'm fighting with a issue:

I added this into the tests: https://github.com/jorge07/tactician-bundle/commit/2bb12cba91060cf176c9b8d7ae5ed8f12726cadc

And I'm having:

```
1) League\Tactician\Bundle\Tests\Integration\BasicCommandAndBusMappingTest::testHandleCommandOnSpecificBus
League\Tactician\Exception\MissingHandlerException: Missing handler for command League\Tactician\Bundle\Tests\EchoText
```

If someone could help me to debug this issue or bring me some light about how to resolve that bug I'll submit the PR ASAP.

Thanks

**Comment by tyx** [comment]
Hello,

I just let a comment on your commit

**Comment by jorge07** [comment]
Awesome. Thanks @tyx for your time, I reviewed the documentation and found that it's also documented.
