### ISSUE TITLE
Symfony 3.3+ support

### ISSUE THREAD

**Issue by adiq** [thephpleague/tactician-bundle#96]
As mentioned in #95: In newer Symfony versions, services are private by default. Beside of that, the naming convention of services has been changed to use FQCN to provide compatibility with the new autowiring feature.

Services should be renamed to use FQCN and be private. To have backward compatibility aliases should be added and marked as public.

See https://symfony.com/doc/current/service_container/3.3-di-changes.html#step-2-using-class-service-id-s for details

**Comment by ogizanagi** [comment]
> the naming convention of services has been changed to use FQCN

Actually the naming convention hasn't changed for third-party bundles. But we can expose FQCN (or Interface FQCN aliases to real services) for service we want to be autowirable. Hence, only a few services should be aliased.

**Comment by rosstuck** [comment]
Hi @adiq,

Thanks for opening this issue and using tactician! Do please try to keep issues to one topic at a time and not mention them across multiple issues. 

As I see it, this privacy topic is being discussed in #95 (which I've reopened). Let's keep talking about it there.

Adding an alias or similar for FQCN is an interesting idea, but is not unique to issues under 3.4, so please open a separate ticket if you'd still like to discuss it. Sorry to sound like a stickler about this but it really helps keep things organized. :)
